Lambda-School-Labs/betterreads-fe

package-lock.json
package.json

Added redux logger as dependency

---

src/index.js

redux logger enabled for use with ReduxDevTools.

redux logger added and enabled for ReduxDevTools

---

readme.md

Badge added to readme.md

---

readme.md

-   [ ] Test A
-   [ ] Test B
-   [ ] …

updated readme with badge

---

src/components/BookDetails.js
src/test/BookDetails.test.js

Adds book search and individual book components
New feature (non-breaking change which adds functionality)
Complete, tested, ready to review and merge
Test A
https://trello.com/c/zN940RiO

got test for bookdetails

---

src/components/search/SearchItem.js

Fixed alignment issues of favorite heart.
-   [ ] Test A
-   [ ] Test B
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works …

Fixed favorite position

---

src/actions/index.js
src/components/common/BookItems.js
src/components/common/BookList.js
src/components/search/Search.js
src/components/search/SearchBreadCrumbs.js
src/components/search/SearchForm.js
src/components/search/SearchList.js
src/reducers/search.js

Refactored the SearchList and SearchItems for reusability. Saves a lot of time!
-   [ ] Test A
-   [ ] Test B
- …

Refactored BookList and BookItems for reusability

---

src/App.js
src/actions/index.js
src/components/common/BookList.js
src/components/common/Breadcrumbs.js
src/components/common/ExternalSearchForm.js
src/components/common/Header.js
src/components/common/ShelfNote.js
src/components/library/Shelf.js
src/components/search/Search.js
src/components/search/SearchForm.js
src/reducers/search.js

Layed out shelf component and other minor changes
New feature (non-breaking change which adds functionality)
Complete, tested, ready to review and merge
Test A

Layed out shelf component and other minor changes

---

src/components/common/BookDetails.js

Styling book details
New feature (non-breaking change which adds functionality)
Complete, tested, ready to review and merge
Test A

Styling book details

---

src/components/common/Breadcrumbs.js
src/components/common/ShelfNote.js
src/components/search/Search.js
src/components/search/SearchForm.js
src/components/search/_SearchItem.js
src/components/search/_SearchList.js

Refactoring components to make reusable.
-   [ ] Test A
-   [ ] Test B
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that …

Styling and component changes and refactoring

---

src/components/common/BookList.js
src/components/common/ShelfNote.js

ShelfNote component updated to receive a single note prop.
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] There are no merge conflicts

ShelfNote component updated

---

src/components/common/BookDetails.js

-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Test A
-   [ ] Test B
-   [ ] …

rewrote conditional statement

---

src/components/common/BookDetails.js

-   [ x ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Test A
-   [ ] Test B
-   [ …

worked on bread crumbs

---

src/components/common/BookDetails.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

formatted code and fixed button

---

src/components/common/BookDetails.js

-   [ x ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Test A
-   [ ] Test B
-   [ …

trying to get books to add

---

src/components/common/BookItems.js
src/components/common/BookList.js
src/components/common/Shelf.js
src/components/common/ShelfContainer.js
src/components/search/Search.js
src/components/search/SearchForm.js

Put user shelves into a separate component.
-   [ ] Test A
-   [ ] Test B
-   [x] I have commented my code, …

Shelf component added

---

src/actions/index.js
src/components/common/BookItems.js
src/components/common/BookList.js
src/components/common/Breadcrumbs.js
src/components/common/Header.js
src/components/common/ShelfNote.js
src/components/search/Search.js
src/components/search/SearchForm.js

Styling updates and function changes to favorite funciton.
-   [ ] Test A
-   [ ] Test B
-   [x] I have …

Search styling and actions updated

---

src/actions/index.js
src/components/common/BookItems.js

Fixed errors with dispatch and dropdown
-   [ ] Test A
-   [ ] Test B
-   [ ] I have commented my code, …

Fixed dispatch error message

---

src/components/common/BookDetails.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

...now with book tracking

---

src/actions/index.js
src/components/authentication/SignIn.js
src/components/authentication/SignUp.js

API URL was incorrect. MUST Fix
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] There are no merge conflicts

API URL fixed

---

readme.md

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Name updated.

---

src/.env
src/actions/index.js
src/components/authentication/SignIn.js
src/components/authentication/SignUp.js
src/components/common/BookDetails.js
src/components/common/BookItems.js

-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] …

took away comma in genre section

---

.gitignore
src/actions/index.js
src/components/common/BookItems.js
src/components/common/BookList.js
src/components/common/ShelfContainer.js
src/components/search/Search.js

Modifying the google book search results to match data that the backend will be providing.
-   [ ] Test A
-   [ ] Test B
-   [x] My code has been reviewed by at least …

Google Search object mods

---

.gitignore
src/.env
src/components/common/BookItems.js
src/components/common/BookList.js
src/components/helpers/index.js
src/components/search/Search.js

Moved functions into a common helper folder.
-   [ ] Test A
-   [ ] Test B
-   [ ] I have commented my code, …

Helper functions created

---

src/.env
src/actions/index.js
src/components/common/BookDetails.js
src/reducers/book.js
src/reducers/index.js

-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Test A
-   [ ] Test B
-   [ ] …

working on refactoring Book details

---

.gitignore
src/components/search/_SearchAgain.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Added missing file

---

src/components/common/BookDetails.js

-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] …

added spacing on genre and fixed thumbnail

---

src/components/common/BookDetails.js
src/components/common/ShelfContainer.js

-   [x] Complete, tested, ready to review and merge
-   [ ] Test A
-   [ ] Test B
-   [ ] …

Shelf container counter

---

src/actions/index.js
src/components/common/BookItems.js
src/components/common/BookList.js
src/components/common/ShelfContainer.js
src/components/helpers/index.js
src/components/library/Library.js
src/components/search/Search.js
src/components/search/_SearchAgain.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Favorite and status functions

---

src/components/helpers/index.js
src/components/search/Search.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

fixed search fetch spacing

---

src/components/helpers/index.js
src/components/search/_SearchAgain.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

Start and End date function added

---

src/components/helpers/index.js
src/components/search/_SearchAgain.js

Delete option added to the dropdown when looking at books in your library or shelves.
-   [ ] Test A
-   [ ] Test B
-   [ ] My code has been reviewed by at least one …

Delete option added. library/shelf only

---

src/actions/index.js
src/components/common/BookList.js
src/components/helpers/index.js
src/components/search/_SearchAgain.js

A little housekeeping.
-   [ ] Test A
-   [ ] Test B
-   [ ] I have commented my code, particularly in …

Cleaning up old code

---

src/components/library/Library.js

-   [x] Complete, but not tested (may need new tests)
-   [ ] Test A
-   [ ] Test B
-   [ ] …

fixed display for finised

---

src/components/common/BookList.js
src/components/helpers/index.js
src/components/search/_SearchAgain.js

If you favorite a book or start tracking, it'll add the bookId and allow you to continue on!
-   [ ] Test A
-   [ ] Test B
-   [ ] My code has been reviewed by at …

Favorite and tracking working together

---

package.json
src/actions/index.js
src/components/common/BookList.js
src/components/helpers/index.js
src/components/library/Library.js
src/components/library/ShelfBook.js
src/components/search/_SearchAgain.js
src/reducers/library.js

Added, Delete book into drop down. Actions created to update a books status, delete and update favorite. And threw in some styling for good measure.
-   [ ] Test A
-   [ ] Test B
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have …

BookCard Magic!

---

src/components/library/Library.js
src/components/search/_SearchAgain.js

Closing bracket missing after last merge.
-   [ ] Test A
-   [ ] Test B
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works …

HOTFIX - closing bracket missing from library.js

---

src/components/authentication/OnboardingQuiz.js
src/test/auth/OnboardingQuiz.test.js
src/test/search/search.test.js

-   [ ] Test A
-   [ ] Test B
-   [ ] …

fixed old tests

---

.github/workflows/ci.yml

-   [ ] Test A
-   [ ] Test B
-   [ ] …

added github workflow ci.yml

---

package.json

-   [ ] Test A
-   [ ] Test B
-   [ ] …

modified  github workflow ci.yml

---

.github/workflows/ci.yml
package.json

-   [ ] Test A
-   [ ] Test B
-   [ ] …

set up yml

---

src/actions/bookActions.js
src/components/common/ShelfSwipe.js
src/components/search/SearchForm.js

categories are sometimes empty. Fixed!

Recommendations fe

---

src/components/common/ShelfSwipe.js
src/components/library/ShelfBook.js
src/components/library/ShelfBookStyle.js

More information added to ShelfBook js.

Added information to ShelfBook

---

src/components/common/StatusShelfCarousel.js
src/components/library/Library.js

Fixed an issue with carousel display

Library tweak

---

src/actions/searchActions.js
src/components/common/BookCard.js
src/components/library/ShelfBook.js

BookCard was not displaying the correct info, one step behind (race condition?). Should be now.

BookCard updating in ShelfBook with correct data

---

src/components/common/AddToExistingShelf.js
src/components/common/CreateNewShelfModalOnPage.js
src/reducers/library.js

styled and got bugs for adding book to library and shelf fixed

---

src/actions/searchActions.js

Now the search is loaded from DS endpoint!

Integrate DS search endpoint

---

src/actions/shelfActions.js

fixed api get

---

src/components/common/Loader.js
src/components/search/Search.js

Loader component added for use when something is loading. Loader takes 2 parameters:
size: string / '24px' (default)
message: string / default: 'Loading, please wait.'

Loader component added and implemented on search

---

src/actions/bookActions.js
src/actions/types.js
src/components/common/AddToExistingShelf.js
src/components/common/BookCard.js
src/components/common/CreateNewShelfModal.js
src/components/common/CreateNewShelfModalOnPage.js
src/components/common/Loader.js
src/components/library/ShelfBook.js
src/reducers/book.js
src/utils/helpers/index.js

Add to shelf styling

---

src/components/common/AddToExistingShelf.js
src/components/common/BookCard.js
src/utils/helpers/index.js

import resolved

---

src/actions/shelfActions.js
src/components/library/ShelfBook.js

ISBN fixed

---

src/components/common/BookCard.js
src/components/library/Shelf.js
src/reducers/library.js

Fixed moving books from one shelf to another from the Shelf component

Fixed moving books from one shelf to another from the Shelf component

---

src/actions/recommendationActions.js
src/components/common/BookCard.js
src/components/common/MyShelves.js
src/components/library/Library.js
src/components/library/Shelves.js
src/reducers/recommendations.js

DS recommendations end point integrated into library.

Ds endpoint integration

---

src/components/common/AddToExistingShelf.js
src/components/common/CreateNewShelfModal.js

Pest control

---

src/components/authentication/Success.js
src/store/actions/authenticationActions.js

- Added grabbing of token from social media logins

ADD Token From Social Media

---

src/store/actions/authenticationActions.js

- Fixed issue with social media
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Complete, tested, ready to review and merge
- [ X ] Ran locally
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My code has been reviewed by at least one peer
- [  X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [ X] There are no merge conflicts

ADD Preserving of State on Google&&Facebook Login

---

src/components/Shelf/CreateNewShelfModal.js
src/components/library/Shelves.js
src/store/actions/libraryActions.js
src/store/actions/shelfActions.js

- Added fix to issue that was calling infinite calls to the api from within a component
Fixes: Reoccuring dependency kept overloading and wouldn't stop running, we assumed it was a dependency array issue.
[X] Bug fix
[X] Complete, tested, ready to review and merge
[X] Tested locally
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My code has been reviewed by at least one peer
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] There are no merge conflicts

FIX Issues with Infinitely Calling API to receive User Shelves

---

.env
.gitignore
src/App.js
src/components/Book/BookCard.js
src/components/Book/BookCardList.js
src/components/Navigation/Header.js
src/components/Shelf/MyShelves.js
src/components/Shelf/StatusShelfCarousel.js
src/components/Shelf/StatusShelfLoading.js
src/components/authentication/OnboardingQuiz.js
src/components/library/Library.js
src/components/library/Shelf.js
src/components/library/ShelfBook.js
src/components/library/styles/RecsStyle.js
src/components/search/SearchForm.js
src/store/actions/authenticationActions.js
src/utils/helpers/index.js

Added Recommendations into application

ADD Recommendations

---

src/components/Book/styles/BookCardListStyle.js

Fixed shelf spacing/styling issue that happened when a shelf had less than 4 books on it
Fixes #171

FIX Shelf Spacing

---

src/components/Book/BookCard.js
src/utils/store.js

FIX Recommendations issue where recommendation were removed after adding to shelf
Fixes #173

FIX Recommendations

---

src/components/Shelf/StatusShelfLoading.js

Changes Recommendation spinner to match the overall theme of the application
Fixes #174 

Changed Recommendation Spinner
